### ISSUE TITLE
Clean up configuration

### ISSUE THREAD

**Issue by swashcap** [MRN-Code/penny-collector#10]
Our schema is in the _config_ directory. Why? This is super confusing, as the schema doesn’t validate a configuration file and it isn’t configuration itself.

File in question: https://github.com/MRN-Code/penny-collector/blob/5ec7c0c0ee03f7c07f8d5863200f86cb5eac183d/config/schema.js

**Comment by swashcap** [comment]
I see this: https://github.com/MRN-Code/penny-collector/blob/5ec7c0c0ee03f7c07f8d5863200f86cb5eac183d/config/schema.js#L19. _WAT._

**Comment by swashcap** [comment]
Also, we should make the schema a static property on `PennyCollector`. No dynamic `require`s! https://github.com/MRN-Code/penny-collector/blob/5ec7c0c0ee03f7c07f8d5863200f86cb5eac183d/src/index.js#L32

**Comment by jwtlake** [comment]
I agree. When we switch to convict everything should be neatly packaged in /src/config.js. Declaration and validation can be defined in the same static file.

**Comment by rssk** [comment]
Related/should be fixed by #15
