### ISSUE TITLE
Update linting to new linting standard

### ISSUE THREAD

**Issue by rssk** [MRN-Code/penny-collector#11]
Update package.json to have our latest linting standards, drop coins-validate.
 [https://github.com/MRN-Code/penny-collector/blob/develop/package.json#L38](url)

**Comment by jwtlake** [comment]
So drop ```javascript "coins-validate": "^5.0.0", ```
What are the new linting standards?

**Comment by jwtlake** [comment]
I used air-bnb's auto installer script to get the latest dependencies.

```
(
  export PKG=eslint-config-airbnb;
  npm info "$PKG" peerDependencies --json | command sed 's/[\{\},]//g ; s/: /@/g' | xargs npm install --save-dev "$PKG"
)
```
https://www.npmjs.com/package/eslint-config-airbnb#eslint-config-airbnb-1

**Comment by jwtlake** [comment]
Created a new branch with the updates.
https://github.com/MRN-Code/penny-collector/tree/feature/lintstandards

- Removed coins-validate
- Used steelpenny as a templete to standardize eslint config 
- Updated lint dependencies to latest

Looks like I'm being punished for using parenthesis on single argument arrow functions. 
```javascript 
// bad
(error) => {}

// good
error => {}
```

As a result there are quite a few linting errors to clean up. Going to wait till after the restructure branch is merged to fix these.
