### ISSUE TITLE
Add a .npmignore file

### ISSUE THREAD

**Issue by swashcap** [MRN-Code/penny-collector#13]
We shouldn’t be shipping our tests or demo code with the shipped package.

**Comment by jwtlake** [comment]
Using one of the coinstac packages as an example I have npm ignoring

- coverage
- docs (shouldn't this be included)
- test

Anything else I should add to the list?

**Comment by swashcap** [comment]
Probably the _config_ directory, the _img_ directory, _.eslintrc.js_, and _TODO.md_. Anything that’s an artifact or isn’t required to actually run the package should be ignored so folks don’t download it.

**Comment by jwtlake** [comment]
created new feature branch to add this file
https://github.com/MRN-Code/penny-collector/blob/feature/npmignore/.npmignore

**Comment by swashcap** [comment]
@jwtlake Don’t forget the _img_ directory!
