### ISSUE TITLE
Investigate configuration passing to PennyCollector#collect

### ISSUE THREAD

**Issue by swashcap** [MRN-Code/penny-collector#18]
This seems odd: https://github.com/MRN-Code/penny-collector/blob/5ec7c0c0ee03f7c07f8d5863200f86cb5eac183d/src/cli.js#L53. Why aren’t we passing configuration during instantiation?

**Comment by rssk** [comment]
Related to issue #20, there is a lot of coupling w/ config and passing the PC instance onto the passed config, this should be changed
