### ISSUE TITLE
Hardcoded deviceModality

### ISSUE THREAD

**Issue by jwtlake** [MRN-Code/penny-collector#22]
https://github.com/MRN-Code/penny-collector/blob/develop/src/models/nifti.js#L60

Can we determine device modality by file type or is this something that needs to be in the user config somehow? Could be interesting if the latter.

**Comment by swashcap** [comment]
Unfortunately, we can’t determine this via file extension. Example: PET scans contain a DICOM file, but they’re their own thing. It sounds like other imaging devices output CSVs, which we’ll need to parse.

**Comment by rssk** [comment]
This has been resolved by discussion yesterday, device modality details ID is no longer a required field in the schema, but now modality is. The modality shall be specified by the processing module.
