### ISSUE TITLE
Remove flags directory

### ISSUE THREAD

**Issue by swashcap** [MRN-Code/penny-collector#31]
WAT: https://github.com/MRN-Code/penny-collector/blob/develop/src/flags/watchjs

We should drop this. If it’s important to persist state it should be in either configuration or some sort of on-disk database.

**Comment by swashcap** [comment]
There’s references to _src/flags/watchjs_ in: _src/transferMeta.js_, _src/watch.js_ and _test/transferMeta.js_. _Hm._

**Comment by ruwang** [comment]
Yes, Jon is working on dropping this and use the internal memory to
maintain the status.

**Comment by rssk** [comment]
Should be solved by #37
