### ISSUE TITLE
Replace node-tus with official tus client

### ISSUE THREAD

**Issue by swashcap** [MRN-Code/penny-collector#34]
It looks like tus has an official client: [tus/tus-js-client](https://github.com/tus/tus-js-client). Why did we roll our own in _[src/tusNodeClient.js](https://github.com/MRN-Code/penny-collector/blob/develop/src/tusNodeClient.js)_?

**Comment by ruwang** [comment]
I think that's for front end?

**Comment by swashcap** [comment]
> I think that's for front end?

The tus client [works in Node.js](https://github.com/tus/tus-js-client#node-compatibility). We should avoid rolling our own unless there’s good reason.

**Comment by ruwang** [comment]
agreed. seems like the `node compatability` was added on Jun 26th after the
transfer logic was implemented in pc.

**Comment by ruwang** [comment]
https://github.com/tus/tus-js-client/commit/044453ea820e0f951e1c518196f905febf99d300#diff-04c6e90faac2675aa89e2176d2eec7d8
